name: sky_wave
description: SkyWave


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  geolocator: ^9.0.2
  http: ^1.1.0
  flutter_spinkit: ^5.2.0
  intl: ^0.18.0
  mrx_charts: ^0.1.3
  awesome_snackbar_content: ^0.1.3
  mccounting_text: ^1.0.0
  flutter_launcher_icons: ^0.13.1
  fl_chart: ^0.63.0

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: PoppinsRegular
      fonts:
        - asset: fonts/Poppins-Regular.ttf

    - family: PoppinsMedium
      fonts:
        - asset: fonts/Poppins-Medium.ttf

    - family: PoppinsSemiBold
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf

    - family: PoppinsBold
      fonts:
        - asset: fonts/Poppins-Bold.ttf

